# Generated by Django 5.2.6 on 2025-09-27 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('types', models.JSONField(default=list)),
                ('counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
