# Generated by Django 5.2.6 on 2025-09-28 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsession',
            name='latest_preview',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='generationsession',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='generationsession',
            table='generation_session',
        ),
        migrations.CreateModel(
            name='RegenerationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('old_question', models.JSONField()),
                ('new_question', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regens', to='api.generationsession')),
            ],
            options={
                'db_table': 'regeneration_log',
                'indexes': [models.Index(fields=['session', 'index'], name='regeneratio_session_d34721_idx')],
            },
        ),
    ]
