# Generated by Django 5.2.6 on 2025-09-28 22:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generationsession_latest_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título personalizado del cuestionario guardado', max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], max_length=10)),
                ('types', models.JSONField(default=list, help_text='Tipos de pregunta habilitados')),
                ('counts', models.JSONField(default=dict, help_text='Cantidad por tipo de pregunta')),
                ('questions', models.JSONField(default=list, help_text='Preguntas generadas del cuestionario')),
                ('user_answers', models.JSONField(default=dict, help_text='Respuestas del usuario {index: respuesta}')),
                ('current_question', models.PositiveIntegerField(default=0, help_text='Índice de la pregunta actual')),
                ('is_completed', models.BooleanField(default=False, help_text='Si el cuestionario fue completado')),
                ('score', models.JSONField(blank=True, default=dict, help_text='Puntaje y detalles de evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Última vez que se accedió al cuestionario')),
            ],
            options={
                'db_table': 'saved_quiz',
                'ordering': ['-last_accessed', '-updated_at'],
                'indexes': [models.Index(fields=['topic', 'difficulty'], name='saved_quiz_topic_1c7885_idx'), models.Index(fields=['created_at'], name='saved_quiz_created_4e8cca_idx'), models.Index(fields=['last_accessed'], name='saved_quiz_last_ac_908ea5_idx'), models.Index(fields=['is_completed'], name='saved_quiz_is_comp_0e463e_idx')],
            },
        ),
    ]
