# Generated by Django 5.2.6 on 2025-10-21 00:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savedquiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_audio', models.BooleanField(default=True)),
                ('save_transcriptions', models.BooleanField(default=True)),
                ('consent_given_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio Privacy Preference',
                'verbose_name_plural': 'Audio Privacy Preferences',
                'db_table': 'audio_privacy_preferences',
            },
        ),
        migrations.CreateModel(
            name='AudioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_sessions',
            },
        ),
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.BinaryField()),
                ('duration_seconds', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_data', to='api.audiosession')),
            ],
            options={
                'db_table': 'audio_data',
            },
        ),
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_redacted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='api.audiosession')),
            ],
            options={
                'db_table': 'audio_transcriptions',
            },
        ),
        migrations.CreateModel(
            name='VoiceMetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Tipo de evento: 'stt_start', 'stt_final', 'tts_complete', 'intent_recognized', etc.", max_length=50)),
                ('session_id', models.UUIDField(blank=True, help_text='UUID de la sesión de audio', null=True)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Latencia en milisegundos', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Score de confianza entre 0 y 1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('intent', models.CharField(blank=True, help_text='Nombre de la intención detectada', max_length=50, null=True)),
                ('backend_used', models.CharField(blank=True, help_text="Backend utilizado: 'grammar', 'gemini', 'perplexity', 'fallback'", max_length=20, null=True)),
                ('text_length', models.IntegerField(blank=True, help_text='Longitud del texto procesado', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado al evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_metric_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AudioDeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('items_deleted', models.JSONField(default=dict)),
                ('deletion_method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_deletion_audits',
                'indexes': [models.Index(fields=['user', 'deleted_at'], name='audio_delet_user_id_6498a7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='audiosession',
            index=models.Index(fields=['expires_at'], name='audio_sessi_expires_7f097b_idx'),
        ),
        migrations.AddIndex(
            model_name='audiosession',
            index=models.Index(fields=['user', 'created_at'], name='audio_sessi_user_id_70846a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiodata',
            index=models.Index(fields=['session', 'recorded_at'], name='audio_data_session_efe47a_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotranscription',
            index=models.Index(fields=['session', 'created_at'], name='audio_trans_session_76eb57_idx'),
        ),
        migrations.AddIndex(
            model_name='voicemetricevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='voice_metri_event_t_995a52_idx'),
        ),
        migrations.AddIndex(
            model_name='voicemetricevent',
            index=models.Index(fields=['user', 'timestamp'], name='voice_metri_user_id_fd0492_idx'),
        ),
        migrations.AddIndex(
            model_name='voicemetricevent',
            index=models.Index(fields=['session_id'], name='voice_metri_session_60a438_idx'),
        ),
    ]
