# Generated by Django 5.2.6 on 2025-10-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_audioprivacypreference_audiosession_audiodata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquiz',
            name='favorite_questions',
            field=models.JSONField(blank=True, default=list, help_text='Lista de índices de preguntas marcadas como favoritas para repaso posterior. Ejemplo: [0, 3, 7] representa las preguntas en las posiciones 0, 3 y 7.'),
        ),
    ]
