# Generated by Django 5.2.6 on 2025-10-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_favorite_questions_to_savedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquiz',
            name='original_quiz',
            field=models.ForeignKey(blank=True, help_text='Si este es un quiz de repaso, referencia al quiz original del que proviene. Permite trazabilidad de la cadena de repaso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_quizzes', to='api.savedquiz'),
        ),
    ]
