# Generated by Django 5.2.6 on 2025-11-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_original_quiz_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsession',
            name='cover_image',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa a la imagen de portada generada', max_length=500),
        ),
        migrations.AddField(
            model_name='savedquiz',
            name='cover_image',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa a la imagen de portada del quiz', max_length=500),
        ),
    ]
