# Generated by Django 5.2.6 on 2025-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_generationsession_cover_image_savedquiz_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsession',
            name='cover_image_history',
            field=models.JSONField(blank=True, default=list, help_text='Lista de rutas de las últimas 3 imágenes generadas, más reciente primero'),
        ),
        migrations.AddField(
            model_name='generationsession',
            name='cover_regeneration_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de regeneraciones de portada realizadas'),
        ),
    ]
