# Generated by Django 5.2.6 on 2025-11-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_generationsession_cover_image_savedquiz_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsession',
            name='image_counts',
            field=models.JSONField(default=dict, help_text="Cantidad de preguntas con imagen por tipo, ej: {'mcq':2,'vf':1}"),
        ),
    ]
