# Generated by Django 5.2.6 on 2025-11-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_generationsession_cover_image_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('prompt', models.TextField()),
                ('provider', models.CharField(default='unknown', max_length=50)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('reused_from_cache', models.BooleanField(default=False)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_generation_log',
            },
        ),
        migrations.CreateModel(
            name='ImagePromptCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('prompt', models.TextField()),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('image_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'image_prompt_cache',
            },
        ),
        migrations.RenameIndex(
            model_name='regenerationlog',
            new_name='regen_session_index_idx',
            old_name='regeneratio_session_d34721_idx',
        ),
        migrations.AddField(
            model_name='imagegenerationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagepromptcache',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_caches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='imagegenerationlog',
            index=models.Index(fields=['user_identifier', 'created_at'], name='image_gener_user_id_c56831_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationlog',
            index=models.Index(fields=['provider', 'created_at'], name='image_gener_provide_471da7_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationlog',
            index=models.Index(fields=['reused_from_cache', 'created_at'], name='image_gener_reused__2c71ea_idx'),
        ),
        migrations.AddIndex(
            model_name='imagepromptcache',
            index=models.Index(fields=['user_identifier', 'prompt_hash', 'expires_at'], name='img_cache_user_prompt_exp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagepromptcache',
            unique_together={('user_identifier', 'prompt_hash')},
        ),
    ]
