# Generated by Django 5.2.6 on 2025-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_imagegenerationlog_imagepromptcache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsession',
            name='image_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Cantidad de preguntas que incluirán imagen por tipo'),
        ),
    ]
