# Generated by Django 5.2.6 on 2025-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_generatedimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedimage',
            new_name='generated_i_user_id_c6b153_idx',
            old_name='api_gene_user_created',
        ),
        migrations.RenameIndex(
            model_name='generatedimage',
            new_name='generated_i_image_r_1e828b_idx',
            old_name='api_gene_image_rel',
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image_rel',
            field=models.CharField(help_text="Ruta relativa dentro de MEDIA_ROOT, p.ej. 'generated/x.png'", max_length=500),
        ),
    ]
