# Generated by Django 5.2.6 on 2025-11-23 01:13

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_api_gene_user_created_generated_i_user_id_c6b153_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedimage',
            new_name='api_gene_user_created',
            old_name='generated_i_user_id_c6b153_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedimage',
            new_name='api_gene_image_rel',
            old_name='generated_i_image_r_1e828b_idx',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='api.generationsession'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image_rel',
            field=models.ImageField(blank=True, db_column='image_rel', help_text='Ruta relativa dentro de MEDIA_ROOT', max_length=255, upload_to=api.models.upload_to_session_imagenes),
        ),
    ]
