# Generated by Django 5.2.6 on 2025-11-23 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_generationsession_image_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('portada', 'Portada'), ('quiz', 'Quiz'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('image_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.generationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_asset',
                'indexes': [models.Index(fields=['session', 'image_type'], name='image_asset_session_c56a3d_idx'), models.Index(fields=['created_at'], name='image_asset_created_045d6b_idx')],
            },
        ),
    ]
