# Generated by Django 5.2.6 on 2025-11-23 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_generated_i_user_id_c6b153_idx_api_gene_user_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='kind',
            field=models.CharField(choices=[('cover', 'cover'), ('question', 'question')], db_index=True, default='question', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['session'], name='api_gene_session_idx'),
        ),
    ]
