# Generated by Django 5.2.6 on 2025-11-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_imagepromptcache_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción/prompt usado para generar la imagen'),
        ),
    ]
